version: '3.8'
services:
  case:
    image: ${DOCKER_REGISTRY-}kafkatask
    ports:
      - 5001:5000
    depends_on:
    - kafka
    networks:
    - kafka-net
    build:
      context: .
      dockerfile: KafkaTask/Dockerfile 
  consumer:
    image: ${DOCKER_REGISTRY-}kafkaconsumer
    ports:
      - 5000:8080
    depends_on:
    - kafka
    networks:
    - kafka-net
    build:
      context: .
      dockerfile: KafkaConsumer/Dockerfile 
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - kafka-net
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-net
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - kafka-net
networks:
  kafka-net:
    driver: bridge